---
format: 1
ctffind4:
  defaults:
    group: EM
    overlay: base
    relstage: unstable
    urls:
      - url: https://grigoriefflab.umassmed.edu/system/tdf?path=ctffind-${V_PKG}-linux64.tar.gz&file=1&type=node&id=26
        name: ctffind-${V_PKG}.tar.gz
    build_variants: first_match
  versions:
    5.0.2:
      config:
        urls:
          - url: https://grigoriefflab.umassmed.edu/system/tdf?path=ctffind-${V_PKG}.tar.gz&file=1&type=node&id=26
            name: ctffind-${V_PKG}.tar.gz
            strip_dirs: 2
    4.1.{8,14}:
      config:
        relstage: stable
