---
format: 1
colabfold:
  defaults:
    group: EM
    overlay: base
    relstage: stable

  versions:
    1.5.5:
      variants:
        - overlay: Alps
          systems: [.*.merlin7.psi.ch]
          relstage: stable
