---
format: 1
chai-1:
  defaults:
    group: EM
    overlay: base
    relstage: stable
  versions:
    0.6.1:
      variants:
        - overlay: Alps
          target_cpus: [x86_64]
          systems: [.*.merlin7.psi.ch]
          relstage: stable
        - overlay: Alps
          target_cpus: [aarch64]
          systems: [gpu0.*.merlin7.psi.ch]
          relstage: stable
