---
format: 1
sevennet:
  defaults:
    group: Tools
    overlay: base
    relstage: stable

  versions:
    0.12.0:
      variants:
        - overlay: base
          target_cpus: [x86_64]
          relstage: stable
          build_requires:
            - clang/20.1.5
            - ffmpeg/4.4
            - gcc/14.2.0
            - cuda/12.9.1
            - openmpi/5.0.8
          runtime_deps:
            - ffmpeg/4.4
            - gcc/14.2.0
            - cuda/12.9.1
            - openmpi/5.0.8
        - overlay: base
          target_cpus: [aarch64]
          relstage: unstable
          build_requires:
            - gcc/14.2.0
            - cuda/12.9.1
            - openmpi/5.0.8
          runtime_deps:
            - gcc/14.2.0
            - cuda/12.9.1
            - openmpi/5.0.8
    0.11.2:
      variants:
        - overlay: base
          target_cpus: [x86_64]
          relstage: stable
          build_requires:
            - clang/20.1.5
            - ffmpeg/4.4
            - gcc/14.2.0
            - cuda/12.9.1
            - openmpi/5.0.8
          runtime_deps:
            - ffmpeg/4.4
            - gcc/14.2.0
            - cuda/12.9.1
            - openmpi/5.0.8
        - overlay: base
          target_cpus: [aarch64]
          relstage: unstable
          build_requires:
            - gcc/14.2.0
            - cuda/12.9.1
            - openmpi/5.0.8
          runtime_deps:
            - gcc/14.2.0
            - cuda/12.9.1
            - openmpi/5.0.8
    0.10.3:
      variants:
        - overlay: base
          target_cpus: [x86_64]
          relstage: stable
          build_requires:
            - clang/20.1.5
            - ffmpeg/4.4
            - gcc/14.2.0
            - cuda/12.9.1
            - openmpi/5.0.8
          runtime_deps:
            - ffmpeg/4.4
            - gcc/14.2.0
            - cuda/12.9.1
            - openmpi/5.0.8
        - overlay: base
          target_cpus: [aarch64]
          relstage: unstable
          build_requires:
            - gcc/14.2.0
            - cuda/12.9.1
            - openmpi/5.0.8
          runtime_deps:
            - gcc/14.2.0
            - cuda/12.9.1
            - openmpi/5.0.8
