---
# yamllint disable rule:line-length
format: 1
trilinos:
  defaults:
    overlay: base
    relstage: stable
    configure_with: cmake
    docfiles:
      - Copyright.txt
      - LICENSE
      - README
      - RELEASE_NOTES
    urls:
      - url: https://github.com/$P/$P/tarball/$P-release-${V//./-}
        name: $P-${V_PKG}.tar.gz

  shasums:

  versions:
    13.4.0:
      variants:
        - systems: [merlin-.*]
          suffix: _slurm
          group: HDF5
          group_deps:
            compiler:
              gcc: [9.5.0, 10.4.0, 11.4.0, 12.3.0]
            mpi:
              openmpi: [4.1.5_slurm]
            hdf5:
              hdf5: [1.10.8_slurm]
        - systems: [merlin-.*]
          suffix: _slurm
          group: HDF5
          group_deps:
            compiler:
              gcc: [10.3.0]
            mpi:
              openmpi: [4.0.5-1_slurm]
            hdf5:
              hdf5: [1.10.7_slurm]
        - systems: [.*]
          group: HDF5
          group_deps:
            compiler:
              gcc: [10.4.0]
            mpi:
              openmpi: [4.1.5]
            hdf5:
              hdf5: [1.10.8]

#trilinos/14.4.0        unstable   HDF5         gcc/10.4.0 openmpi/4.1.5 hdf5/1.10.8

#trilinos/11.10.2       deprecated MPI          gcc/4.7.4 openmpi/1.6.5
#trilinos/11.10.2       deprecated MPI          gcc/4.7.4 openmpi/1.8.2
#trilinos/11.10.2       deprecated MPI          gcc/4.7.4 openmpi/1.8.4
#trilinos/11.10.2       deprecated MPI          gcc/4.8.3 openmpi/1.6.5
#trilinos/11.10.2       deprecated MPI          gcc/4.8.3 openmpi/1.8.2
#trilinos/11.10.2       deprecated MPI          gcc/4.8.3 openmpi/1.8.4
#trilinos/11.10.2       deprecated MPI          gcc/4.8.4 openmpi/1.6.5
#trilinos/11.10.2       deprecated MPI          gcc/4.8.4 openmpi/1.8.2
#trilinos/11.10.2       deprecated MPI          gcc/4.8.4 openmpi/1.8.4
#trilinos/11.10.2       deprecated MPI          gcc/4.9.2 openmpi/1.6.5
#trilinos/11.10.2       deprecated MPI          gcc/4.9.2 openmpi/1.8.2
#trilinos/11.10.2       deprecated MPI          gcc/4.9.2 openmpi/1.8.4

#trilinos/11.12.1       deprecated MPI          gcc/4.7.4 openmpi/1.6.5
#trilinos/11.12.1       deprecated MPI          gcc/4.7.4 openmpi/1.8.2
#trilinos/11.12.1       deprecated MPI          gcc/4.7.4 openmpi/1.8.4
#trilinos/11.12.1       deprecated MPI          gcc/4.8.3 openmpi/1.6.5
#trilinos/11.12.1       deprecated MPI          gcc/4.8.3 openmpi/1.8.2
#trilinos/11.12.1       deprecated MPI          gcc/4.8.3 openmpi/1.8.4
#trilinos/11.12.1       deprecated MPI          gcc/4.8.4 openmpi/1.6.5
#trilinos/11.12.1       deprecated MPI          gcc/4.8.4 openmpi/1.8.2
#trilinos/11.12.1       deprecated MPI          gcc/4.8.4 openmpi/1.8.4
#trilinos/11.12.1       deprecated MPI          gcc/4.9.2 openmpi/1.6.5
#trilinos/11.12.1       deprecated MPI          gcc/4.9.2 openmpi/1.8.2
#trilinos/11.12.1       deprecated MPI          gcc/4.9.2 openmpi/1.8.4

#trilinos/11.14.1       deprecated MPI          gcc/4.7.4 openmpi/1.6.5
#trilinos/11.14.1       deprecated MPI          gcc/4.7.4 openmpi/1.8.2
#trilinos/11.14.1       deprecated MPI          gcc/4.7.4 openmpi/1.8.4
#trilinos/11.14.1       deprecated MPI          gcc/4.8.3 openmpi/1.6.5
#trilinos/11.14.1       deprecated MPI          gcc/4.8.3 openmpi/1.8.2
#trilinos/11.14.1       deprecated MPI          gcc/4.8.3 openmpi/1.8.4
#trilinos/11.14.1       deprecated MPI          gcc/4.8.4 openmpi/1.6.5
#trilinos/11.14.1       deprecated MPI          gcc/4.8.4 openmpi/1.8.2
#trilinos/11.14.1       deprecated MPI          gcc/4.8.4 openmpi/1.8.4
#trilinos/11.14.1       deprecated MPI          gcc/4.9.2 openmpi/1.6.5
#trilinos/11.14.1       deprecated MPI          gcc/4.9.2 openmpi/1.8.2
#trilinos/11.14.1       deprecated MPI          gcc/4.9.2 openmpi/1.8.4

#trilinos/11.14.3       deprecated MPI          gcc/4.8.5 openmpi/1.10.2
#trilinos/11.14.3       deprecated MPI          gcc/6.2.0 openmpi/1.10.2
#trilinos/11.14.3       deprecated MPI          gcc/6.2.0 openmpi/1.10.4
#trilinos/11.14.3       deprecated MPI          gcc/6.2.0 openmpi/2.0.1
#trilinos/11.14.3       deprecated MPI          intel/15.3 openmpi/1.8.4

#trilinos/12.2.1        deprecated HDF5         gcc/4.8.2 openmpi/1.6.5 hdf5/1.8.12

#trilinos/12.8.1        deprecated MPI          gcc/4.8.5 openmpi/1.10.4
#trilinos/12.8.1        deprecated MPI          gcc/4.9.4 openmpi/1.10.4
#trilinos/12.8.1        deprecated MPI          gcc/5.4.0 openmpi/1.10.4
#trilinos/12.8.1        deprecated MPI          gcc/6.2.0 openmpi/1.10.4

#trilinos/12.10.1       deprecated MPI          gcc/4.8.5 openmpi/1.10.4
#trilinos/12.10.1       deprecated MPI          gcc/4.9.4 openmpi/1.10.4
#trilinos/12.10.1       deprecated MPI          gcc/5.4.0 openmpi/1.10.4
#trilinos/12.10.1       deprecated MPI          gcc/6.2.0 openmpi/1.10.4

#trilinos/12.10.1-1     deprecated HDF5         gcc/5.4.0 openmpi/1.10.4 hdf5/1.8.18
#trilinos/12.10.1-1     deprecated HDF5         gcc/6.2.0 openmpi/1.10.4 hdf5/1.8.18

#trilinos/12.10.1-2     deprecated HDF5         gcc/5.4.0 openmpi/1.10.4 hdf5/1.8.18

#trilinos/12.10.1-3     deprecated HDF5         gcc/5.4.0 openmpi/1.10.4 hdf5/1.8.18

#trilinos/12.12.1       deprecated HDF5         gcc/7.3.0 mpich/3.3 hdf5/1.10.4
#trilinos/12.12.1       deprecated HDF5         gcc/7.3.0 openmpi/1.10.7 hdf5/1.10.1
#trilinos/12.12.1       deprecated HDF5         gcc/7.3.0 openmpi/2.1.2 hdf5/1.10.1
#trilinos/12.12.1       deprecated HDF5         gcc/7.3.0 openmpi/3.0.0 hdf5/1.10.1
#trilinos/12.12.1       deprecated HDF5         gcc/7.3.0 openmpi/3.1.2 hdf5/1.10.3
#trilinos/12.12.1       deprecated HDF5         gcc/7.3.0 openmpi/3.1.3 hdf5/1.10.4
#trilinos/12.12.1       deprecated HDF5         gcc/7.4.0 openmpi/3.1.4 hdf5/1.10.5
#trilinos/12.12.1       deprecated HDF5         intel/17.4 openmpi/1.10.7 hdf5/1.10.1
#trilinos/12.12.1       deprecated HDF5         intel/17.4 openmpi/2.1.2 hdf5/1.10.1
#trilinos/12.12.1       deprecated HDF5         intel/17.4 openmpi/3.0.0 hdf5/1.10.1

#trilinos/12.18.1       stable     HDF5         gcc/7.5.0 openmpi/3.1.6 hdf5/1.10.6
#trilinos/12.18.1       stable     HDF5         gcc/8.4.0 openmpi/3.1.6 hdf5/1.10.6
#trilinos/12.18.1       stable     HDF5         gcc/9.3.0 openmpi/3.1.6 hdf5/1.10.6
#trilinos/12.18.1       stable     HDF5         gcc/10.1.0 openmpi/3.1.6 hdf5/1.10.6
#trilinos/12.18.1_slurm stable     HDF5         gcc/7.5.0 openmpi/3.1.6_slurm hdf5/1.10.6_slurm
#trilinos/12.18.1_slurm stable     HDF5         gcc/8.4.0 openmpi/3.1.6_slurm hdf5/1.10.6_slurm
#trilinos/12.18.1_slurm stable     HDF5         gcc/9.3.0 openmpi/3.1.6_slurm hdf5/1.10.6_slurm

#trilinos/13.0.1        stable     HDF5         gcc/7.5.0 openmpi/4.0.5 hdf5/1.10.7
#trilinos/13.0.1        stable     HDF5         gcc/8.4.0 openmpi/4.0.5 hdf5/1.10.7
#trilinos/13.0.1        stable     HDF5         gcc/9.3.0 openmpi/4.0.5 hdf5/1.10.7
#trilinos/13.0.1        stable     HDF5         gcc/10.3.0 openmpi/4.0.5 hdf5/1.10.7
#trilinos/13.0.1        stable     HDF5         gcc/10.4.0 openmpi/4.1.4 hdf5/1.10.8
#trilinos/13.0.1_slurm  stable     HDF5         gcc/10.3.0 openmpi/4.0.5-1_slurm hdf5/1.10.7_slurm
#trilinos/13.0.1_slurm  stable     HDF5         gcc/10.4.0 openmpi/4.1.4_slurm hdf5/1.10.8_slurm


