---
format: 1
alphafold3:
  defaults:
    group: EM
    overlay: base
    relstage: unstable

  versions:
    3.0.1:
      variants:
        - overlay: Alps
          systems: [.*.merlin7.psi.ch]
          relstage: unstable
