overlay: base
relstage: stable
cmake/2.8.12.2:
cmake/3.1.3:
cmake/3.3.2:
cmake/3.4.1:
cmake/3.6.3:
cmake/3.9.6:
cmake/3.10.3:
- dependencies: b:gcc/7.3.0
cmake/3.13.3:
- dependencies: b:gcc/7.3.0
cmake/3.14.0:
- dependencies: b:gcc/7.3.0
cmake/3.15.5:
- dependencies: b:gcc/7.3.0 b:patchelf/0.8.1
cmake/3.19.2:
- dependencies: b:gcc/8.4.0 b:patchelf/0.8.1
cmake/3.20.5:
- dependencies: b:gcc/8.4.0 b:patchelf/0.8.1
cmake/3.23.2:
- dependencies: b:gcc/8.4.0 b:patchelf/0.8.1
  relstage: stable
