---
format: 1
chimerax:
  defaults:
    group: EM
    overlay: base
    relstage: stable

  versions:
    1.10:
      variants:
        - overlay: Alps
          systems: [.*.merlin7.psi.ch]
          relstage: stable
    1.11:
      variants:
        - overlay: Alps
          systems: [.*.merlin7.psi.ch]
          relstage: stable
