---
# yamllint disable rule:line-length
format: 1
amrex:
  defaults:
    group: MPI
    overlay: base
    relstage: stable
    configure_with: cmake
    use_flags: [3d]
    docfiles:
      - CHANGES
      - INSTALL
      - license.txt
      - README.txt
    urls:
      - url: https://github.com/AMReX-Codes/$P/archive/${V_PKG}.tar.gz
        name: $P-${V_PKG}.tar.gz

  shasums:

  versions:
    18.07.1:
      variants:
        - systems: [merlin-.*]
          suffix: _3d_slurm
          group_deps:
            compiler:
              gcc: [10.4.0, 11.4.0, 12.3.0, 13.1.0]
            mpi:
              openmpi: [4.1.5_slurm]
        - systems: [.*]
          suffix: _3d
          group_deps:
            compiler:
              gcc: [10.4.0]
            mpi:
              openmpi: [4.1.5]

    18.07:
      variants:
        - systems: [merlin-.*]
          suffix: _3d_slurm
          group_deps:
            compiler:
              gcc: [7.5.0, 8.4.0, 9.3.0]
            mpi:
              openmpi: [3.1.6_slurm]
        - systems: [merlin-.*]
          suffix: _3d_slurm
          group_deps:
            compiler:
              gcc: [10.3.0, 10.4.0]
            mpi:
              openmpi: [4.0.5-1_slurm]
        - systems: [merlin-.*]
          suffix: _3d_slurm
          group_deps:
            compiler:
              gcc: [10.4.0]
            mpi:
              openmpi: [4.1.4_slurm]
        - systems: [.*]
          suffix: _3d
          group_deps:
            compiler:
              gcc: [7.3.0, 8.2.0]
            mpi:
              mpich: [3.2.1]
        - systems: [.*]
          suffix: _3d
          group_deps:
            compiler:
              gcc: [7.5.0, 8.4.0, 9.3.0]
            mpi:
              openmpi: [3.1.6]
        - systems: [.*]
          suffix: _3d
          group_deps:
            compiler:
              gcc: [7.5.0, 8.4.0, 9.3.0, 10.3.0]
            mpi:
              openmpi: [4.0.5]
        - systems: [.*]
          suffix: _3d
          group_deps:
            compiler:
              gcc: [10.4.0]
            mpi:
              openmpi: [4.1.4]
