---
# yamllint disable rule:line-length
format: 1
impi:
  defaults:
    group: Compiler
    overlay: base
    relstage: stable
    build_functions:
      prep: []
      configure: []
      compile: []
      install: []

  versions:
    22.2:
      variants:
        - systems: [merlin-.*\.psi.ch]
          group_deps:
            compiler:
              intel: [22.2]

    22.1:
      variants:
        - systems: [merlin-.*\.psi.ch]
          group_deps:
            compiler:
              intel: [22.1]

    21.4:
      variants:
        - systems: [merlin-.*\.psi.ch]
          group_deps:
            compiler:
              intel: [21.4]

    20.4:
      variants:
        - systems: [merlin-.*\.psi.ch]
          group_deps:
            compiler:
              intel: [20.4]

    19.4:
      variants:
        - systems: [merlin-.*\.psi.ch]
          relstage: deprecated
          group_deps:
            compiler:
              intel: [19.4]

    19.3:
      variants:
        - systems: [merlin-.*\.psi.ch]
          relstage: deprecated
          group_deps:
            compiler:
              intel: [19.3]

    18.4:
      variants:
        - systems: [merlin-.*\.psi.ch]
          relstage: deprecated
          group_deps:
            compiler:
              intel: [18.4]
    18.3:
      variants:
        - systems: [merlin-.*\.psi.ch]
          relstage: deprecated
          group_deps:
            compiler:
              intel: [18.3]

    18.2:
      variants:
        - systems: [merlin-.*\.psi.ch]
          relstage: deprecated
          group_deps:
            compiler:
              intel: [18.2]
 
   17.8:
      variants:
        - systems: [merlin-.*\.psi.ch]
          relstage: deprecated
          group_deps:
            compiler:
              intel: [17.8]

   5.1:
      variants:
        - systems: [merlin-.*\.psi.ch]
          relstage: deprecated
          group_deps:
            compiler:
              intel: [16.1, 16.2, 16.3, 17.1]
   5.0:
      variants:
        - systems: [merlin-.*\.psi.ch]
          relstage: deprecated
          group_deps:
            compiler:
              intel: [15.2, 15.3]

